services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: go-app
    hostname: go-app
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge