x-kafka:
  image: &x-kafka-image
    confluentinc/cp-kafka:8.3.0
x-kafka_controller:
  entrypoint: &kafka-controller-entrypoint
    [ "/bin/bash", "-c", "unset KAFKA_ADVERTISED_LISTENERS; exec /etc/confluent/docker/run" ]
  env: &kafka_controller-env
    CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    
    KAFKA_HEAP_OPTS: "-Xms512m -Xmx1g"
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
    KAFKA_LISTENERS: "CONTROLLER://:9093"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:SSL"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_PROCESS_ROLES: "controller"
    
    KAFKA_SSL_TRUSTSTORE_TYPE: "JKS"
    KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
    KAFKA_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
    KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
    
    KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
    KAFKA_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
    
    KAFKA_SSL_KEY_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEY_CREDENTIALS: "sslkey_creds"
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
    KAFKA_SSL_CLIENT_AUTH: "required"
    
    # Включаем авторизацию
    KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
    KAFKA_SUPER_USERS: "User:CN=admin,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=mirror-maker,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-ui,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=schema-registry,L=Moscow,OU=Practice,O=Yandex,C=RU;"

x-kafka_broker:
  env: &kafka-broker-env
    CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    KAFKA_HEAP_OPTS: "-Xms512m -Xmx1g"
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
    KAFKA_LISTENERS: "EXTERNAL://:9094,SSL://:9093"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SSL,SSL:SSL,CONTROLLER:SSL"
    KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_PROCESS_ROLES: "broker"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    
    KAFKA_SSL_TRUSTSTORE_TYPE: "JKS"
    KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
    KAFKA_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
    KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
    
    KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
    KAFKA_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
    
    KAFKA_SSL_KEY_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEY_CREDENTIALS: "sslkey_creds"
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
    KAFKA_SSL_CLIENT_AUTH: "required"
    
    # Включаем авторизацию
    KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
    KAFKA_SUPER_USERS: "User:CN=admin,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-b-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-c-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=mirror-maker,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-ui,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=schema-registry,L=Moscow,OU=Practice,O=Yandex,C=RU;"

x-kafka2:
  image: &x-kafka2-image
           confluentinc/cp-kafka:8.3.0
x-kafka2_controller:
  entrypoint: &kafka2-controller-entrypoint
    [ "/bin/bash", "-c", "unset KAFKA_ADVERTISED_LISTENERS; exec /etc/confluent/docker/run" ]
  env: &kafka2_controller-env
    CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Ql"

    KAFKA_HEAP_OPTS: "-Xms512m -Xmx1g"
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "7@kafka2-c-1:9093,8@kafka2-c-2:9093,9@kafka2-c-3:9093"
    KAFKA_LISTENERS: "CONTROLLER://:9093"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:SSL"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_PROCESS_ROLES: "controller"

    KAFKA_SSL_TRUSTSTORE_TYPE: "JKS"
    KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
    KAFKA_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
    KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"

    KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
    KAFKA_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"

    KAFKA_SSL_KEY_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEY_CREDENTIALS: "sslkey_creds"
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
    KAFKA_SSL_CLIENT_AUTH: "required"

    # Включаем авторизацию
    KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
    KAFKA_SUPER_USERS: "User:CN=admin,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=mirror-maker,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-ui,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=schema-registry,L=Moscow,OU=Practice,O=Yandex,C=RU;"

x-kafka2_broker:
  env: &kafka2-broker-env
    CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Ql"
    KAFKA_HEAP_OPTS: "-Xms512m -Xmx1g"
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "7@kafka2-c-1:9093,8@kafka2-c-2:9093,9@kafka2-c-3:9093"
    KAFKA_LISTENERS: "EXTERNAL://:9095,SSL://:9093"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SSL,SSL:SSL,CONTROLLER:SSL"
    KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_PROCESS_ROLES: "broker"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    KAFKA_SSL_TRUSTSTORE_TYPE: "JKS"
    KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
    KAFKA_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
    KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"

    KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
    KAFKA_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
    KAFKA_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"

    KAFKA_SSL_KEY_PASSWORD: "${CA_PASS}"
    KAFKA_SSL_KEY_CREDENTIALS: "sslkey_creds"
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
    KAFKA_SSL_CLIENT_AUTH: "required"

    # Включаем авторизацию
    KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
    KAFKA_SUPER_USERS: "User:CN=admin,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-b-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-1,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-2,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka2-c-3,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=mirror-maker,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=kafka-ui,L=Moscow,OU=Practice,O=Yandex,C=RU;User:CN=schema-registry,L=Moscow,OU=Practice,O=Yandex,C=RU;"

services:
  kafka-c-1:
    image: *x-kafka-image
    entrypoint: *kafka-controller-entrypoint
    container_name: kafka-c-1
    hostname: kafka-c-1
    environment:
      <<: *kafka_controller-env
      KAFKA_NODE_ID: 1
    volumes:
      - kafka-c-1-data:/var/lib/kafka/data
      - ./mount_dir/kafka-c-1/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka-c-2:
    image: *x-kafka-image
    entrypoint: *kafka-controller-entrypoint
    container_name: kafka-c-2
    hostname: kafka-c-2
    environment:
      <<: *kafka_controller-env
      KAFKA_NODE_ID: 2
    volumes:
      - kafka-c-2-data:/var/lib/kafka/data
      - ./mount_dir/kafka-c-2/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka-c-3:
    image: *x-kafka-image
    entrypoint: *kafka-controller-entrypoint
    container_name: kafka-c-3
    hostname: kafka-c-3
    environment:
      <<: *kafka_controller-env
      KAFKA_NODE_ID: 3
    volumes:
      - kafka-c-3-data:/var/lib/kafka/data
      - ./mount_dir/kafka-c-3/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka-b-1:
    image: *x-kafka-image
    container_name: kafka-b-1
    hostname: kafka-b-1
    environment:
      <<: *kafka-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:19094,SSL://kafka-b-1:9093"
      KAFKA_NODE_ID: 4
    volumes:
      - kafka-b-1-data:/var/lib/kafka/data
      - ./mount_dir/kafka-b-1/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "19094:9094"

  kafka-b-2:
    image: *x-kafka-image
    container_name: kafka-b-2
    hostname: kafka-b-2
    environment:
      <<: *kafka-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:29094,SSL://kafka-b-2:9093"
      KAFKA_NODE_ID: 5
    volumes:
      - kafka-b-2-data:/var/lib/kafka/data
      - ./mount_dir/kafka-b-2/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "29094:9094"

  kafka-b-3:
    image: *x-kafka-image
    container_name: kafka-b-3
    hostname: kafka-b-3
    environment:
      <<: *kafka-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:39094,SSL://kafka-b-3:9093"
      KAFKA_NODE_ID: 6
    volumes:
      - kafka-b-3-data:/var/lib/kafka/data
      - ./mount_dir/kafka-b-3/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "39094:9094"

  kafka2-c-1:
    image: *x-kafka2-image
    entrypoint: *kafka2-controller-entrypoint
    container_name: kafka2-c-1
    hostname: kafka2-c-1
    environment:
      <<: *kafka2_controller-env
      KAFKA_NODE_ID: 7
    volumes:
      - kafka2-c-1-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-c-1/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka2-c-2:
    image: *x-kafka2-image
    entrypoint: *kafka2-controller-entrypoint
    container_name: kafka2-c-2
    hostname: kafka2-c-2
    environment:
      <<: *kafka2_controller-env
      KAFKA_NODE_ID: 8
    volumes:
      - kafka2-c-2-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-c-2/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka2-c-3:
    image: *x-kafka2-image
    entrypoint: *kafka2-controller-entrypoint
    container_name: kafka2-c-3
    hostname: kafka2-c-3
    environment:
      <<: *kafka2_controller-env
      KAFKA_NODE_ID: 9
    volumes:
      - kafka2-c-3-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-c-3/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped

  kafka2-b-1:
    image: *x-kafka2-image
    container_name: kafka2-b-1
    hostname: kafka2-b-1
    environment:
      <<: *kafka2-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:19095,SSL://kafka2-b-1:9093"
      KAFKA_NODE_ID: 10
    volumes:
      - kafka2-b-1-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-b-1/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "19095:9095"

  kafka2-b-2:
    image: *x-kafka2-image
    container_name: kafka2-b-2
    hostname: kafka2-b-2
    environment:
      <<: *kafka2-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:29095,SSL://kafka2-b-2:9093"
      KAFKA_NODE_ID: 11
    volumes:
      - kafka2-b-2-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-b-2/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "29095:9095"

  kafka2-b-3:
    image: *x-kafka2-image
    container_name: kafka2-b-3
    hostname: kafka2-b-3
    environment:
      <<: *kafka2-broker-env
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://${CRT_ALT_NAMES_IP_2}:39095,SSL://kafka2-b-3:9093"
      KAFKA_NODE_ID: 12
    volumes:
      - kafka2-b-3-data:/var/lib/kafka/data
      - ./mount_dir/kafka2-b-3/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "39095:9095"

  mirror-maker:
    build:
      context: .
      dockerfile: docker/mirror-maker/Dockerfile
    container_name: mirror-maker
    environment:
      LOG4J_LOGGERS: "org.apache.kafka=DEBUG,org.apache.kafka.connect.mirror=DEBUG"

      # Внутренние топики храним в ЦЕЛЕВОМ кластере (второй)
      CONNECT_BOOTSTRAP_SERVERS: "kafka2-b-1:9093,kafka2-b-2:9093,kafka2-b-3:9093"
      CONNECT_GROUP_ID: "mirror-maker-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "mirror-maker-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "mirror-maker-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "mirror-maker-status"

      # Дополнительные настройки для безопасности
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
    volumes:
      - ./mount_dir/mirror-maker/creds:/etc/kafka/secrets/source
      - ./mount_dir/mirror-maker/creds:/etc/kafka/secrets/target
      - ./mount_dir/mirror-maker/config:/etc/mirror-maker
    networks:
      - kafka-network
    depends_on:
      - kafka-b-1
      - kafka-b-2
      - kafka-b-3
      - kafka2-b-1
      - kafka2-b-2
      - kafka2-b-3
    restart: unless-stopped

  kafka-connect:
    image: confluentinc/cp-kafka-connect:8.3.0
    container_name: kafka-connect
    hostname: kafka-connect
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-b-1:9093,kafka-b-2:9093,kafka-b-3:9093"
      CONNECT_GROUP_ID: "connect-file-sink"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.json.JsonSchemaConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "https://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_KEY_PASSWORD: "${CA_PASS}"
      CONNECT_PLUGIN_PATH: "/usr/share/java/,/usr/share/confluent-hub-components/,/usr/share/filestream-connectors/"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      # SSL
      CONNECT_SECURITY_PROTOCOL: "SSL"
      CONNECT_SSL_TRUSTSTORE_TYPE: "JKS"
      CONNECT_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      CONNECT_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_SSL_KEYSTORE_TYPE: "PKCS12"
      CONNECT_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      CONNECT_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_SSL_KEY_PASSWORD: "${CA_PASS}"
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"

      # REST API
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LISTENERS: "https://:8083"
      CONNECT_REST_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      CONNECT_REST_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_REST_SSL_KEY_PASSWORD: "${CA_PASS}"

      # Consumer SSL (наследуется task-коннекторами)
      CONNECT_CONSUMER_SECURITY_PROTOCOL: "SSL"
      CONNECT_CONSUMER_SSL_TRUSTSTORE_TYPE: "JKS"
      CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_CONSUMER_SSL_KEYSTORE_TYPE: "PKCS12"
      CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      CONNECT_CONSUMER_SSL_KEY_PASSWORD: "${CA_PASS}"
      CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
    volumes:
      - ./mount_dir/kafka-connect/creds:/etc/kafka/secrets
      - ./mount_dir/kafka-connect/output:/var/lib/kafka-connect-data
    ports:
      - "8083:8083"
    networks:
      - kafka-network
    depends_on:
      - kafka-b-1
      - kafka-b-2
      - kafka-b-3
    restart: unless-stopped

  # Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:8.3.0
    container_name: schema-registry
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_COMPATIBILITY_LEVEL: "FULL"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-b-1:9093,kafka-b-2:9093,kafka-b-3:9093"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "SSL"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: "/etc/schema-registry/secrets/truststore.jks"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: "/etc/schema-registry/secrets/keystore.pkcs12"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_LISTENERS: "https://0.0.0.0:8081"
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "https"
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: "/etc/schema-registry/secrets/keystore.pkcs12"
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: "/etc/schema-registry/secrets/truststore.jks"
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: "${CA_PASS}"
      SCHEMA_REGISTRY_SSL_CLIENT_AUTH: true
      SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: "10000"
    volumes:
      - ./mount_dir/schema-registry/creds:/etc/schema-registry/secrets
    ports:
      - "8081:8081"
    networks:
      - kafka-network
    depends_on:
      - kafka-b-1
      - kafka-b-2
      - kafka-b-3
      - kafka2-b-1
      - kafka2-b-2
      - kafka2-b-3
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka-b-1:9093,kafka-b-2:9093,kafka-b-3:9093"
      KAFKA_CLUSTERS_0_NAME: "kafka-kraft"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: "JKS"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_CREDENTIALS: "sslkey_creds"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"

      KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS: "kafka2-b-1:9093,kafka2-b-2:9093,kafka2-b-3:9093"
      KAFKA_CLUSTERS_1_NAME: "kafka2-kraft"
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: "SSL"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/truststore.jks"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_TYPE: "JKS"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_FILENAME: "truststore.jks"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/keystore.pkcs12"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_FILENAME: "keystore.pkcs12"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEY_PASSWORD: "${CA_PASS}"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEY_CREDENTIALS: "sslkey_creds"
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"


      #  Подключение к Schema Registry
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "https://schema-registry:8081"
      KAFKA_CLUSTERS_1_SCHEMAREGISTRY: "https://schema-registry:8081"
    volumes:
      - ./mount_dir/kafka-ui/creds:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    depends_on:
      - kafka-c-1
      - kafka-c-2
      - kafka-c-3
      - kafka-b-1
      - kafka-b-2
      - kafka-b-3
      - schema-registry

volumes:
  kafka-c-1-data:
  kafka-c-2-data:
  kafka-c-3-data:
  kafka-b-1-data:
  kafka-b-2-data:
  kafka-b-3-data:
  kafka2-c-1-data:
  kafka2-c-2-data:
  kafka2-c-3-data:
  kafka2-b-1-data:
  kafka2-b-2-data:
  kafka2-b-3-data:

networks:
  kafka-network:
    driver: bridge