services:
  kafka-c-1:
    image: confluentinc/cp-kafka:8.3.0
    # Для роли контроллера "KAFKA_ADVERTISED_LISTENERS" должна отсутствовать, но в поставке cp-kafka, она все равно создается. Поэтому вот так удаляем ее.
    entrypoint: [ "/bin/bash", "-c", "unset KAFKA_ADVERTISED_LISTENERS; exec /etc/confluent/docker/run" ]
    container_name: kafka-c-1
    hostname: kafka-c-1
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "controller"
      # SSL настройки
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/ssl_key_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"
      
      KAFKA_CONTROLLER_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_SSL_VERIFY_HOSTNAME: "true"
      KAFKA_SSL_TRUSTMANAGER_ALGORITHM: "PKIX"
      
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
      - kafka-c-1-data:/var/lib/kafka/data
      - ./ssl/controllers/kafka-c-1:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
  kafka-c-2:
    image: confluentinc/cp-kafka:8.3.0
    # Для роли контроллера "KAFKA_ADVERTISED_LISTENERS" должна отсутствовать, но в поставке cp-kafka, она все равно создается. Поэтому вот так удаляем ее.
    entrypoint: [ "/bin/bash", "-c", "unset KAFKA_ADVERTISED_LISTENERS; exec /etc/confluent/docker/run" ]
    container_name: kafka-c-2
    hostname: kafka-c-2
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "controller"
      # SSL настройки
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/ssl_key_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"
      
      KAFKA_CONTROLLER_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_SSL_VERIFY_HOSTNAME: "true"
      KAFKA_SSL_TRUSTMANAGER_ALGORITHM: "PKIX"
      
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
        - kafka-c-2-data:/var/lib/kafka/data
        - ./ssl/controllers/kafka-c-2:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
  kafka-c-3:
    image: confluentinc/cp-kafka:8.3.0
    # Для роли контроллера "KAFKA_ADVERTISED_LISTENERS" должна отсутствовать, но в поставке cp-kafka, она все равно создается. Поэтому вот так удаляем ее.
    entrypoint: [ "/bin/bash", "-c", "unset KAFKA_ADVERTISED_LISTENERS; exec /etc/confluent/docker/run" ]
    container_name: kafka-c-3
    hostname: kafka-c-3
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "CONTROLLER://:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "controller"
      # SSL настройки
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/ssl_key_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"
      
      KAFKA_CONTROLLER_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_SSL_VERIFY_HOSTNAME: "true"
      KAFKA_SSL_TRUSTMANAGER_ALGORITHM: "PKIX"
      
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
        - kafka-c-3-data:/var/lib/kafka/data
        - ./ssl/controllers/kafka-c-3:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
  kafka-b-1:
    image: confluentinc/cp-kafka:8.3.0
    container_name: kafka-b-1
    hostname: kafka-b-1
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 4
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-b-1:9092,SSL://kafka-b-1:9093,EXTERNAL://127.0.0.1:19094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SSL:SSL,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # SSL настройки
      # --- ЭТО ОБЯЗАТЕЛЬНО, чтобы не было ошибки "variable not set" ---
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"

      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_PROTOCOL: "TLSv1.3"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
      - kafka-b-1-data:/var/lib/kafka/data
      - ./ssl/brokers/kafka-b-1:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "19094:9094"
  kafka-b-2:
    image: confluentinc/cp-kafka:8.3.0
    container_name: kafka-b-2
    hostname: kafka-b-2
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 5
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-b-2:9092,SSL://kafka-b-2:9093,EXTERNAL://127.0.0.1:29094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SSL:SSL,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # SSL настройки
      # --- ЭТО ОБЯЗАТЕЛЬНО, чтобы не было ошибки "variable not set" ---
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_PROTOCOL: "TLSv1.3"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
      - kafka-b-2-data:/var/lib/kafka/data
      - ./ssl/brokers/kafka-b-2:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "29094:9094"
  kafka-b-3:
    image: confluentinc/cp-kafka:8.3.0
    container_name: kafka-b-3
    hostname: kafka-b-3
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 6
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-c-1:9093,2@kafka-c-2:9093,3@kafka-c-3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-b-3:9092,SSL://kafka-b-3:9093,EXTERNAL://127.0.0.1:39094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,SSL:SSL,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      # SSL настройки
      # --- ЭТО ОБЯЗАТЕЛЬНО, чтобы не было ошибки "variable not set" ---
      KAFKA_SSL_KEYSTORE_FILENAME: "ssl/keystore.p12"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEY_CREDENTIALS: "creds/keystore_creds"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "creds/keystore_creds"
      
      KAFKA_SSL_TRUSTSTORE_FILENAME: "ssl/truststore.p12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "creds/truststore_creds"
      KAFKA_SSL_ENABLED_PROTOCOLS: "TLSv1.3,TLSv1.2"
      KAFKA_SSL_PROTOCOL: "TLSv1.3"
      KAFKA_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      KAFKA_SSL_KEYMANAGER_ALGORITHM: "SunX509"
      KAFKA_OPTS: "-Djdk.tls.client.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -Djdk.tls.server.cipherSuites=TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    volumes:
      - kafka-b-3-data:/var/lib/kafka/data
      - ./ssl/brokers/kafka-b-3:/etc/kafka/secrets
    networks:
      - kafka-network
    restart: unless-stopped
    ports:
      - "39094:9094"
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka-b-1:9093,kafka-b-2:9093,kafka-b-3:9093"
      KAFKA_CLUSTERS_0_NAME: "kafka-kraft"
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: "/etc/ssl/truststore.p12"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: "kafka123"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: "/etc/ssl/keystore.p12"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: "kafka123"
      KAFKA_CONTROLLER_SSL_TRUSTMANAGER_ALGORITHM: "PKIX"
    volumes:
      - ./ssl/clients/ssl:/etc/ssl
    networks:
      - kafka-network
    restart: unless-stopped
    depends_on:
      - kafka-c-1
      - kafka-c-2
      - kafka-c-3
      - kafka-b-1
      - kafka-b-2
      - kafka-b-3
  app:
      build:
          context: .
          dockerfile: docker/Dockerfile
      container_name: go-app
      hostname: go-app
      restart: unless-stopped
      networks:
          - kafka-network

volumes:
  kafka-c-1-data:
  kafka-c-1-secrets:
  kafka-c-2-data:
  kafka-c-2-secrets:
  kafka-c-3-data:
  kafka-c-3-secrets:
  kafka-b-1-data:
  kafka-b-2-data:
  kafka-b-3-data:

networks:
  kafka-network:
    driver: bridge